DROP TABLE paths IF EXISTS;
DROP TABLE snapshots IF EXISTS;
DROP SEQUENCE global_seq IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ AS INTEGER START WITH 100000;

CREATE TABLE snapshots
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  date_time        TIMESTAMP    NOT NULL,
  dir              VARCHAR(255) NOT NULL,
  dirs_count       INTEGER      NOT NULL,
  files_count      INTEGER      NOT NULL,
  total_size       BIGINT       NOT NULL
);
CREATE UNIQUE INDEX snapshots_unique_date_time_dir_idx ON snapshots (date_time, dir);

CREATE TABLE paths
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name             VARCHAR(255) NOT NULL,
  size             BIGINT,
  snapshot_id      INTEGER      NOT NULL,
  FOREIGN KEY (snapshot_id) REFERENCES snapshots (id) ON DELETE CASCADE
);
